### ISSUE TITLE
v2.3.1 TypeError: o.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by jorisroling** [apollographql/apollo-client#3426]
Since we upgraded to v2.3.1 we see this error: "TypeError: o.hasOwnProperty is not a function".
A fix for it has been presented in this [MR](https://github.com/apollographql/apollo-client/pull/3418) 

Hope that helps!
