### ISSUE TITLE
v3.5.0+ ApolloClient.mutate() type error: Property 'errors' does not exist

### ISSUE THREAD

**Issue by harsh0596** [apollographql/apollo-client#9292]
call `mutate` using `ApolloClient` class:

```
let result = client.mutate(...)
```

try to access `errors`:

```
console.log(result.errors)
```

error:

`Property 'errors' does not exist on type 'FetchResult<any, Record<string, any>, Record<string, any>>'.`

works on 3.4.0

**Comment by jebenois** [comment]
Ran into the same issue while trying to upgrade.

**Comment by LeSphax** [comment]
This is caused by having an incompatible version of the graphql package. Upgrading from 14 to 16.0.1 fixed this for me.

**Comment by ErlanBelekov** [comment]
@LeSphax didn't help in my case, still getting the error even on `"graphql": "16.0.1"`

**Comment by jpvajda** [comment]
👋  Hello everyone! Would you be willing to upgrade to `[3.6.7](https://github.com/apollographql/apollo-client/releases/tag/v3.6.7)` and let us know if you are still seeing this problem?

**Comment by ErlanBelekov** [comment]
@jpvajda the issue is still there at v3.6.9 
`Property 'errors' does not exist on type 'FetchResult<MyMutation, Record<string, any>, Record<string, any>>'`

Code:

```
const res = await replyToDealVerificationRequest({
      variables: {
        input: {
          dealID,
          isVerified: false,
          ...({ description } || {}),
        },
      },
    })

    if (res.errors && res.errors.length) {
      toast({
        title: 'Rejection failed',
        description: String((res as any).errors[0].message),
      })
    }
```

Relevant dependencies(with `dev` ones):
```
"@apollo/client": "^3.6.9",
"@apollo/link-context": "^2.0.0-beta.3",
"apollo-upload-client": "^17.0.0",
"graphql": "^15.5.0",
"@graphql-codegen/cli": "^1.21.5",
"@graphql-codegen/typescript": "^1.22.1",
"@graphql-codegen/typescript-operations": "^1.18.0",
"@graphql-codegen/typescript-react-apollo": "^2.2.5",
"@types/apollo-upload-client": "^17.0.0",
```

**Comment by trevorglick** [comment]
ran into the same issue as @ErlanBelekov just upgraded to 3.6.9

**Comment by ludwigkaube** [comment]
for me it worked again after upgrading to `graphql`:`16.6.0` & `@apollo/client`: `3.7.7`

**Comment by cmslewis** [comment]
I'm experiencing this, too. I tried upgrading to `graphql@16.6.0` and `@apollo/client@3.7.7` and was still seeing this problem. But explicitly casting as `SingleExecutionResult` (imported from `@apollo/client`) seems to fix the problem.

```tsx
// Must explicitly type to appease TS - for some reason the FetchResult type union isn't
// resolving to the proper subtype.
//
// See: https://github.com/apollographql/apollo-client/issues/9292
const results: SingleExecutionResult[] = await Promise.all(promises);
```

Would be curious to know if this workaround works for anyone else.

**Comment by rbmdotdev** [comment]
same problem here with client 3.8.8 and graphql 16.8.1

**Comment by phryneas** [comment]
Could you create some kind of reproduction for this?

If you try this [TypeScript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgQUgGzRAwm4BTAO3gF84AzKCEOAcgAEBDdTAegGNdCYaAoHgEzwcGUPHDYQCAZ3gd8RAFwpm2TkQA8DAgE8AfDzR54ZI2wAWAJTxSArmngBeOAwDuDYLLUwAdCBswGGDwACgRSBilnHQBKPhMYcytbe288KEooKR4WFjg8-IK4AD0AfiA), it's there.

(Screenshot shows 3.9.4)
![image](https://github.com/apollographql/apollo-client/assets/4282439/96879788-eec1-461d-be15-1e4a2c9a8117)


Same for versions 3.5.0
![image](https://github.com/apollographql/apollo-client/assets/4282439/be67a2f1-2b41-4df3-a7d3-13f14cf2fa31)

and version 3.8.8
![image](https://github.com/apollographql/apollo-client/assets/4282439/13749444-ba05-4a51-a6fd-7300b7577bb3)
