### ISSUE TITLE
[3.9.0] inFlightLinkObservables_1.remove is not a function (it is undefined) in react-native

### ISSUE THREAD

**Issue by efstathiosntonas** [apollographql/apollo-client#11543]
### Issue Description

After upgrading from 3.8.10 on react-native 0.73.3 I get this error: `inFlightLinkObservables_1.remove is not a function (it is undefined)`

I created an empty react-native project, transferred over my client setup and I do **not** get this error in a simple query (without graphql-codegen). I'm using latest @graphql-codegen to create my types/hooks. Cannot figure out why this is throwing so this issue is more like "help me on what might cause that".

This is the place where this throws:
https://github.com/apollographql/apollo-client/blob/85fb665bfd0383ea5e4d368f9450ba42ff92e398/src/core/QueryManager.ts#L1139

when I console log the [entry](https://github.com/apollographql/apollo-client/blob/85fb665bfd0383ea5e4d368f9450ba42ff92e398/src/core/QueryManager.ts#L1126):

```json
{"observable":{"observers":{},"promise":{"_h":1,"_i":1,"_j":{"data":{"account_by_pk":{"id":"M5txLRYc5TMeDzknV9DUNaDoAHl2","email":"test@test.com","first_name":"Günther","last_name":"Test","onboarding_completed":true,"__typename":"account"}}},"_k":null},"handlers":{},"nextResultListeners":{},"sources":[],"sub":null,"latest":["next",{"data":{"account_by_pk":{"id":"M5txLRYc5TMeDzknV9DUNaDoAHl2","email":"test@test.com","first_name":"Günther","last_name":"Test","onboarding_completed":true,"__typename":"account"}}}]}}
```

`concast` console.log:

```json
{"observers":{},"promise":{"_h":1,"_i":0,"_j":null,"_k":{"onFulfilled":null,"promise":{"_h":0,"_i":0,"_j":null,"_k":null}}},"handlers":{},"nextResultListeners":{},"sources":[],"sub":{"_observer":{},"_state":"ready"}}
```

`inFlightLinkObservables` console.log:

```json
{"weakness":false,"strong":{}}
```

eslint went nuts after the update:
![Screenshot 2024-01-31 at 09 07 59](https://github.com/apollographql/apollo-client/assets/717975/d1b80ced-faf8-4df9-aa98-5a43e2894024)

ps. This line should be removed? 🤔 https://github.com/apollographql/apollo-client/blob/85fb665bfd0383ea5e4d368f9450ba42ff92e398/src/core/QueryManager.ts#L192  (don't think it will make any difference, just pointing out)

### Link to Reproduction

no-repro

### Reproduction Steps

Update from 3.8.10 to 3.9.0 in a react-native project.

### `@apollo/client` version

3.9.0

**Comment by efstathiosntonas** [comment]
I think the problem is with Hermes `WeakRef`: https://github.com/facebook/react-native/issues/42742

**Comment by alessbell** [comment]
Great find, @efstathiosntonas, and funny timing: I see it was opened yesterday with tracking issues on the Hermes project going back to at least 2021.

That does seem possibly relevant, but `toBeGarbageCollected.ts` contains testing matchers used by our Apollo Client test suite that shouldn't wind up in your bundle. One of our maintainers is out sick today and I'm still investigating this, thanks for your patience.

**Comment by efstathiosntonas** [comment]
@alessbell you're right 🤦 , should have noticed the file path!

**Comment by alessbell** [comment]
Thanks for sharing your demo, @efstathiosntonas (moving our thread over here 😊).

> please note that i cannot reproduce it

I also can't reproduce it in our `rn-apollo-client-testbed` repo that uses codegen (all dependencies on `latest`). Can you confirm which versions you're using of all relevant dependencies?

**Comment by efstathiosntonas** [comment]
these are the codegen versions:

```json
{
 "@graphql-codegen/add": "5.0.0",
    "@graphql-codegen/cli": "5.0.0",
    "@graphql-codegen/fragment-matcher": "5.0.0",
    "@graphql-codegen/introspection": "4.0.0",
    "@graphql-codegen/jsdoc": "3.0.0",
    "@graphql-codegen/typescript": "4.0.1",
    "@graphql-codegen/typescript-apollo-client-helpers": "3.0.0",
    "@graphql-codegen/typescript-operations": "4.0.1",
    "@graphql-codegen/typescript-react-apollo": "4.1.0",
    "@graphql-eslint/eslint-plugin": "3.20.1",
}

and codegen.yml:

```yml
schema:
  - "http://localhost:9091/v1/graphql":
      headers:
        x-hasura-admin-secret: myadminsecretkey
#  - "directive @connection(key: String, filter: [String]) on FIELD"
watch: true
require:
  - ts-node/register
documents: 'src/**/*.graphql'
emitLegacyCommonJSImports: false
config:
  scalars:
    DateTime: Date
    JSON: "{ [key: string]: any }"
    timestamptz: string
    numeric: number
overwrite: true
generates:
  ./src/generated/apollo-helpers.ts:
    plugins:
      - typescript-apollo-client-helpers
  ./src/generated/graphql.tsx:
    schema: schema.json
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
      - 'jsdoc'
      - add:
          content: "/* eslint-disable */"
    config:
      constEnums: true
      #immutableTypes: true
      preResolveTypes: true
      defaultMapper: any
      reactApolloVersion: 3
      skipTypename: false
      avoidOptionals: true
      maybeValue: T
      withHooks: true
      withComponent: false
      withHOC: false
      withRefetchFn: true
    hooks:
      afterOneFileWrite:
        - prettier --write
  ./src/graphql.schema.json:
    plugins:
      - "introspection"
    config:
      minify: true
    hooks:
      afterOneFileWrite:
        - prettier --write
  ./src/generated/fragments.tsx:
   plugins:
     - fragment-matcher
     - add:
         content: "/* eslint-disable */"
   config:
     useExplicitTyping: true
   hooks:
     afterAllFileWrite:
       - prettier --write
```

**Comment by alessbell** [comment]
Aha, that would do it! Out of curiosity: do you remember why you pinned that in the first place? Hoping that resolves the eslint errors you're seeing too :)

**Comment by alessbell** [comment]
Glad to hear it, @efstathiosntonas!

**Comment by efstathiosntonas** [comment]
@alessbell just an update, eslint errors are not gone, I guess this is codegen issue now.

**Comment by alessbell** [comment]
@efstathiosntonas would you mind opening a separate issue for that and I'll x-link to your comment above? Will take a look, thanks!
