### ISSUE TITLE
Typescript error with RequestInfo

### ISSUE THREAD

**Issue by UnknownJeff** [apollographql/apollo-client#11736]
### Issue Description

We are running into a type script error after upgrading to Apollo/client 3.8.9 and we are not quite sure why.

The stack-trace is as follows: 

```bash
 error TS2322: Type '(uri: RequestInfo, options: RequestInit) => Promise<Response>' is not assignable to type '{ (input: RequestInfo | URL, init?: RequestInit | undefined): Promise<Response>; (input: string | Request | URL, init?: RequestInit | undefined): Promise<...>; }'.
  Types of parameters 'uri' and 'input' are incompatible.
    Type 'RequestInfo | URL' is not assignable to type 'RequestInfo'.
      Type 'URL' is not assignable to type 'RequestInfo'.

34     fetch: (uri: RequestInfo, options: RequestInit) => {
```

and the code snippet that produces the error is as follow: 

```js
const httpLink = createHttpLink({
    uri: foo,
    fetch: (uri: RequestInfo, options: RequestInit) => {
      options.headers = getHeaders();
      return fetch(uri, options).then((response) => {
        if (response.status >= 500) {
          return Promise.reject(response.status);
        }
        return response;
      });
    }
  });
```
I checked the change logs for this version and I did not notice anything obvious that changed for the types so any help is greatly appreciated.

Other possible useful version numbers:
vue@3.3.8
vuetify@3.4.3
types/node@20.11.30

### Link to Reproduction

Not possible in this case

### Reproduction Steps

Fails during build after updating package.json to 3.8.9. Nothing else as changed with the code. Downgrading back to Apollo/Client@3.8.8 results in a successful build. 3.8.9 and above causes it to fail with the error above. 

### `@apollo/client` version

3.8.9

**Comment by jerelmiller** [comment]
Hey @UnknownJeff 👋 

Sorry to hear you're having issues! I'm willing to bet its related to https://github.com/apollographql/apollo-client/pull/11449 which removed dependence on the `dom` library in TypeScript since you can use Apollo Client in non-browser environments. The type of `fetch` now relies on `typeof fetch` which should be found in `@types/node`. Not sure if an update to `@types/node` would help or not here?

**Comment by jerelmiller** [comment]
Oh wait, I see you're manually typing the `fetch` function yourself. You should be able to rely on type inference here, so perhaps try removing the explicit types for the arguments?

```diff
- fetch: (uri: RequestInfo, options: RequestInit) => {
+ fetch: (uri, options) => {
```

Doing so should then just use the types that `createHttpLink` provides for the `fetch` function instead. See if this helps!

**Comment by UnknownJeff** [comment]
That along with a minor tweak worked perfectly. Thanks for the quick assist.
