### ISSUE TITLE
After 1.2.1 release can't build the project.

### ISSUE THREAD

**Issue by kruszyk** [apollographql/apollo-client#4537]
**Intended outcome:**

Intended outcome : project builds. 

I am using Apollo in my Angular 6 project. 6 days ago it stops compiling, 

**Actual outcome:**

Actual outcome: Project fails to build. Error I am getting is :+1: 

ERROR in node_modules/apollo-cache-inmemory/node_modules/apollo-utilities/lib/util/mergeDeep.d.ts(2,52): error TS2370: A rest parameter must be of an array type.

**How to reproduce the issue:**

Not sure how to reproduce it. In my case it was working one day and it stopped next day without any changes. I guess apollo-utilities library went from 1.1.3 to 1.2.1

**Versions**

System:
    OS: Linux 3.10 CentOS Linux 7 (Core)
  Binaries:
    Node: 8.9.4 - /usr/local/bin/node
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 72.0.3626.121
    Firefox: 60.5.1
  npmPackages:
    apollo-angular: ^1.5.0 => 1.5.0 
    apollo-angular-link-http: ^1.5.0 => 1.5.0 
    apollo-cache-inmemory: ^1.4.3 => 1.4.3 
    apollo-client: ^2.4.13 => 2.4.13 
    apollo-link: ^1.2.8 => 1.2.8

**Comment by pl12133** [comment]
Which version of `typescript` are you running? Upgrading your versions may help resolve the issue, please see https://github.com/apollographql/apollo-client/issues/4506#issuecomment-469098232.

**Comment by cheungyinglon** [comment]
+1

**Comment by kruszyk** [comment]
@pl12133 

I am building project with 2.9.2, which is highest I can go I believe.

**Comment by hebby** [comment]
I met the same problem.

` ERROR in node_modules/apollo-link-http-common/node_modules/apollo-utilities/lib/util/mergeDeep.d.ts(2,52): error TS2370: A rest parameter must be of an array type.`

+-- apollo-link-http@1.5.9
| `-- apollo-link-http-common@0.2.11
|   `-- apollo-link@1.2.9
|     `-- apollo-utilities@1.2.1

building with typescript 2.9.2

**Comment by darmie** [comment]
I am having this problem too

**Comment by niklasR** [comment]
We're having the same issue.

**Comment by niklasR** [comment]
I'm also experiencing this With TS 2.9.2, however on another machine it seems to work with utilities 1.2.1 and TS 2.9.2.. Continuing investigation.

**Comment by darmie** [comment]
This fixed it for me.

https://github.com/apollographql/apollo-client/issues/4501#issuecomment-468099291

**Comment by benjamn** [comment]
Duplicate of #4506 (and also #4501).
