### ISSUE TITLE
With TypeScript, Apollo Client expects to be built with `lib: ['dom']`, which is non-ideal for non-browser environments and not documented

### ISSUE THREAD

**Issue by jrnail23** [apollographql/apollo-client#6376]
@benjamn, I just installed the RC, and got the following typescript errors, all from DOM types (my project is a lib that doesn't depend on any DOM stuff).  FYI, my previous version was beta 52, which didn't have this problem.
```

packages/my-project/node_modules/@apollo/client/link/http/parseAndCheckHttpResponse.d.ts:3:15 - error TS2304: Cannot find name 'Response'.

3     response: Response;
                ~~~~~~~~

packages/my-project/node_modules/@apollo/client/link/http/parseAndCheckHttpResponse.d.ts:7:100 - error TS2304: Cannot find name 'Response'.

7 export declare function parseAndCheckHttpResponse(operations: Operation | Operation[]): (response: Response) => Promise<any>;
                                                                                                     ~~~~~~~~

packages/my-project/node_modules/@apollo/client/link/utils/throwServerError.d.ts:2:15 - error TS2304: Cannot find name 'Response'.

2     response: Response;
                ~~~~~~~~

packages/my-project/node_modules/@apollo/client/link/utils/throwServerError.d.ts:6:51 - error TS2304: Cannot find name 'Response'.

6 export declare const throwServerError: (response: Response, result: any, message: string) => never;
                                                    ~~~~~~~~

packages/my-project/node_modules/@apollo/client/link/http/selectHttpOptionsAndBody.d.ts:14:13 - error TS2304: Cannot find name 'WindowOrWorkerGlobalScope'.

14     fetch?: WindowOrWorkerGlobalScope['fetch'];
               ~~~~~~~~~~~~~~~~~~~~~~~~~

packages/my-project/node_modules/@apollo/client/link/http/checkFetcher.d.ts:1:46 - error TS2304: Cannot find name 'WindowOrWorkerGlobalScope'.

1 export declare const checkFetcher: (fetcher: WindowOrWorkerGlobalScope['fetch'] | undefined) => void;
                                               ~~~~~~~~~~~~~~~~~~~~~~~~~

packages/my-project/node_modules/@apollo/client/link/http/createSignalIfSupported.d.ts:5:17 - error TS2304: Cannot find name 'AbortController'.

5     controller: AbortController;
                  ~~~~~~~~~~~~~~~

packages/my-project/node_modules/@apollo/client/link/http/createSignalIfSupported.d.ts:6:13 - error TS2304: Cannot find name 'AbortSignal'.

6     signal: AbortSignal;
              ~~~~~~~~~~~
```

**Comment by balazsorban44** [comment]
May be related, after upgrading to 3.0.0-rc.0, I get the following error:

```
Type 'import("/project/node_modules/@apollo/link-context/node_modules/@apollo/client/link/core/ApolloLink").ApolloLink' is not assignable 
to type 'import("/project/node_modules/@apollo/client/link/core/ApolloLink").ApolloLink'.
```

Downgrading back to beta 50 (my previous version) does NOT solve the issue.


The relevant code:
```ts
import { ApolloClient, createHttpLink } from "@apollo/client"
import { setContext } from "@apollo/link-context"

const authLink = setContext(async (_, { headers }) => {
  // REVIEW:
  // Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
  // Maybe: https://stackoverflow.com/questions/7042340/error-cant-set-headers-after-they-are-sent-to-the-client
  const token = await getToken("withApollo")
  return {
    headers: {
      ...headers,
      Authorization: token ? `Bearer ${token}` : "",
    },
  }
})


//...
new ApolloClient({
    cache: new InMemoryCache(cacheConfig),
    connectToDevTools: process.env.NODE_ENV === "development",
   // TS error occurring here
   // Type 'import("/project/node_modules/@apollo/link-context/node_modules/@apollo/client/link/core/ApolloLink").ApolloLink' is not assignable 
   // to type 'import("/project/node_modules/@apollo/client/link/core/ApolloLink").ApolloLink'.
   // The expected type comes from property 'link' which is declared here on type 'ApolloClientOptions<NormalizedCacheObject>'
    link: authLink.concat(httpLink),
    uri: process.env.NEXT_PUBLIC_CONTENT_API,
  })
```

**Comment by RadoslavK** [comment]
I had the same issue with error link. You can  try adding
```
"resolutions": {
    "@apollo/link-context/@apollo/client": "3.0.0-rc.0"
  },
```
to your `package.json`. It worked for me.

**Comment by jrnail23** [comment]
Unfortunately, `resolutions` is a yarn thing. I'm on npm.

**Comment by hwillson** [comment]
It sounds like this was resolved - closing, thanks!

**Comment by sammoh94** [comment]
@jrnail23 how did you resolve this?

**Comment by jrnail23** [comment]
@sammoh94, I don't know if I ever did resolve it, TBH.  It's been a while since I worked on that stuff 🤷

**Comment by sirugh** [comment]
I fixed the errors by adding `dom` to the lib array.

**Comment by jtomaszewski** [comment]
This issue shouldn't be closed. Adding `dom` shouldn't be a solution - this client should be working in node.js services (which do not rely on DOM) without problems.

We are hitting this now on `@apollo/client` v3.3.16 .

**Comment by hwillson** [comment]
Thanks for confirming this is a problem in 3.3.16 - we'll take a look.

**Comment by ysfaran** [comment]
Any updates?

This is still present: `"@apollo/client": "^3.4.10"

**Comment by magrinj** [comment]
@hwillson Any update on this ?
This is still present on 3.5.10

**Comment by anamariapetrescu** [comment]
Any updates? I still have this problem as well for v3.5.10.

**Comment by effektsvk** [comment]
@glasser Was that commit supposed to close the issue?

**Comment by glasser** [comment]
Heh, I didn't know you could close issues across repositories... or I would have been more careful writing "Apollo Client could fix https://github.com/apollographql/apollo-client/issues/6376".

**Comment by glasser** [comment]
I took the liberty of updating the PR title.

**Comment by bilalq** [comment]
Still a problem in `3.7.9`. There are 4 `.d.ts` files causing the impact.

```
node_modules/@apollo/client/link/http/checkFetcher.d.ts:1:46 - error TS2304: Cannot find name 'WindowOrWorkerGlobalScope'.

1 export declare const checkFetcher: (fetcher: WindowOrWorkerGlobalScope['fetch'] | undefined) => void;
                                               ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@apollo/client/link/http/parseAndCheckHttpResponse.d.ts:4:15 - error TS2304: Cannot find name 'Response'.

4     response: Response;
                ~~~~~~~~

node_modules/@apollo/client/link/http/parseAndCheckHttpResponse.d.ts:8:97 - error TS2304: Cannot find name 'Response'.

8 export declare function readMultipartBody<T extends object = Record<string, unknown>>(response: Response, observer: Observer<T>): Promise<void>;
                                                                                                  ~~~~~~~~

node_modules/@apollo/client/link/http/parseAndCheckHttpResponse.d.ts:10:52 - error TS2304: Cannot find name 'Response'.

10 export declare function parseJsonBody<T>(response: Response, bodyText: string): T;
                                                      ~~~~~~~~

node_modules/@apollo/client/link/http/parseAndCheckHttpResponse.d.ts:12:77 - error TS2304: Cannot find name 'Response'.

12 export declare function readJsonBody<T = Record<string, unknown>>(response: Response, operation: Operation, observer: Observer<T>): void;
                                                                               ~~~~~~~~

node_modules/@apollo/client/link/http/parseAndCheckHttpResponse.d.ts:13:100 - error TS2304: Cannot find name 'Response'.

13 export declare function parseAndCheckHttpResponse(operations: Operation | Operation[]): (response: Response) => Promise<any>;
                                                                                                      ~~~~~~~~

node_modules/@apollo/client/link/http/selectHttpOptionsAndBody.d.ts:18:13 - error TS2304: Cannot find name 'WindowOrWorkerGlobalScope'.

18     fetch?: WindowOrWorkerGlobalScope['fetch'];
               ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@apollo/client/link/utils/throwServerError.d.ts:2:15 - error TS2304: Cannot find name 'Response'.

2     response: Response;
                ~~~~~~~~

node_modules/@apollo/client/link/utils/throwServerError.d.ts:6:51 - error TS2304: Cannot find name 'Response'.

6 export declare const throwServerError: (response: Response, result: any, message: string) => never;
                                                    ~~~~~~~~


Found 9 errors in 4 files.

Errors  Files
     1  node_modules/@apollo/client/link/http/checkFetcher.d.ts:1
     5  node_modules/@apollo/client/link/http/parseAndCheckHttpResponse.d.ts:4
     1  node_modules/@apollo/client/link/http/selectHttpOptionsAndBody.d.ts:18
     2  node_modules/@apollo/client/link/utils/throwServerError.d.ts:2
```

**Comment by phryneas** [comment]
Hey there!
Since `@types/node` is now shipping `fetch` types, too, it looks like we can drop the `"dom"` dependencies now.

Could you please give the PR build from #11449 a try?
```sh
npm i @apollo/client@0.0.0-pr-11449-20231222103407
```

For those of you who can't even install the `node` types, you'll have to add a `types.d.ts` to your project with contents like
```ts
const fetch: (
  input: RequestInfo | URL,
  init?: RequestInit
) => Promise<Response>;
type RequestInfo = Request | string;
interface RequestInit {}
interface Request {}
interface Response {}
```

**Comment by clemlatz** [comment]
Hey @phryneas!

I tried 
```
npm i @apollo/client@0.0.0-pr-11449-20231222103407
```
but it didn't change anything for me.


Then I tried

```
 npm install @types/node  
```

and it made it a little better, but I'm still seeing two errors:
```
node_modules/@apollo/client/link/http/checkFetcher.d.ts:1:46 - error TS2304: Cannot find name 'WindowOrWorkerGlobalScope'.

1 export declare const checkFetcher: (fetcher: WindowOrWorkerGlobalScope["fetch"] | undefined) => void;
                                               ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@apollo/client/link/http/selectHttpOptionsAndBody.d.ts:32:13 - error TS2304: Cannot find name 'WindowOrWorkerGlobalScope'.

32     fetch?: WindowOrWorkerGlobalScope["fetch"];
               ~~~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors in 2 files.

Errors  Files
     1  node_modules/@apollo/client/link/http/checkFetcher.d.ts:1
     1  node_modules/@apollo/client/link/http/selectHttpOptionsAndBody.d.ts:32
```

In the end, I was only able to have Typescript compile my code by adding "dom" to the tsconfig.json `lib` array.

**Comment by phryneas** [comment]
Hi @clemlatz, 
I believe something went wrong with the installation of the PR build in your case. 😞  
Maybe you ended up with two versions of `@apollo/client`? 

If you look at the file that is giving you an error, it has a completely different content in that new version:
https://unpkg.com/@apollo/client@0.0.0-pr-11449-20231222103407/link/http/checkFetcher.d.ts

**Comment by clemlatz** [comment]
Indeed, I can confirm that 

```shell
rm -rf node_modules
npm i @apollo/client@0.0.0-pr-11449-20231222103407 @types/node  
```

fixed the problem!

Thanks for your help.

**Comment by phryneas** [comment]
This will be included in the next patch release.
