### ISSUE TITLE
'InMemoryCacheConfig' locally, but it is not exported when upgrading @apollo/client from 3.4.10 to 3.4.16

### ISSUE THREAD

**Issue by chenrui333** [apollographql/apollo-client#9029]
### Discussed in https://github.com/apollographql/apollo-client/discussions/9027

<div type='discussions-op-text'>

<sup>Originally posted by **chenrui333** November  8, 2021</sup>
```
Error: src/providers/apolloClient.ts(14,10): error TS2459: Module '"@apollo/client/cache/inmemory/inMemoryCache"' declares 'InMemoryCacheConfig' locally, but it is not exported.
```</div>
